services:

  mysql:
    image: mysql:8.4
    container_name: order-management-mysql

    environment:
      MYSQL_DATABASE: order_management
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  app:
    image: priy75/order-management:latest
    container_name: order-management-app

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata

    ports:
      - "8080:8080"

volumes:
  mysql_data: