  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:

      - name: Pull latest Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/order-management:latest

      - name: Stop and remove old application container
        run: |
          docker stop order-management-app 2>$null
          docker rm -f order-management-app 2>$null

      - name: Run new application container
        run: |
          docker run -d `
            --name order-management-app `
            -p 8080:8080 `
            -e SPRING_DATASOURCE_URL="jdbc:mysql://host.docker.internal:3307/order_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata" `
            -e SPRING_DATASOURCE_USERNAME="root" `
            -e SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" `
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" `
            ${{ secrets.DOCKERHUB_USERNAME }}/order-management:latest