name: Order Management CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: order_management
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/order_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata

    steps:

      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

      - name: Set up Docker Buildx
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-management:latest


  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:

      - name: Pull latest Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/order-management:latest

      - name: Stop and remove old application container
        run: |
          docker stop order-management-app 2>$null
          docker rm -f order-management-app 2>$null

      - name: Run new application container
        run: |
          docker run -d `
            --name order-management-app `
            -p 8080:8080 `
            -e SPRING_DATASOURCE_URL="jdbc:mysql://host.docker.internal:3307/order_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata" `
            -e SPRING_DATASOURCE_USERNAME="root" `
            -e SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" `
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" `
            ${{ secrets.DOCKERHUB_USERNAME }}/order-management:latest